/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clientes;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Esteban
 */
public class VentanaCliente extends javax.swing.JFrame {
    Cliente usuario;
    /**
     * Creates new form VentanaCliente
     */
    public VentanaCliente() {
        initComponents();
        try {
            usuario = new Cliente(this);
            usuario.conexion();
        } catch (IOException ex) {
            Logger.getLogger(VentanaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaUsers = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaNotifications = new javax.swing.JTextArea();
        txfFollow = new javax.swing.JTextField();
        btnFollow = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaFollowersFollowing = new javax.swing.JTextArea();
        txfPost = new javax.swing.JTextField();
        btnPost = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaBoard = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txaUsers.setColumns(20);
        txaUsers.setRows(5);
        jScrollPane1.setViewportView(txaUsers);

        txaNotifications.setColumns(20);
        txaNotifications.setRows(5);
        jScrollPane2.setViewportView(txaNotifications);

        txfFollow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfFollowActionPerformed(evt);
            }
        });

        btnFollow.setText("Seguir");
        btnFollow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFollowActionPerformed(evt);
            }
        });

        txaFollowersFollowing.setColumns(20);
        txaFollowersFollowing.setRows(5);
        jScrollPane3.setViewportView(txaFollowersFollowing);

        txfPost.setText("¿Que piensas?");
        txfPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPostActionPerformed(evt);
            }
        });

        btnPost.setText("Publicar");
        btnPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");

        jButton1.setText("jButton1");

        txaBoard.setColumns(20);
        txaBoard.setRows(5);
        jScrollPane4.setViewportView(txaBoard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txfFollow)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFollow)
                        .addGap(23, 23, 23))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txfPost, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPost)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfFollow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFollow))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfFollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfFollowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfFollowActionPerformed

    private void btnFollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFollowActionPerformed
        try {
        String mensaje = txfFollow.getText();
        txfFollow.setText("");
        usuario.salida.writeInt(1);
        usuario.salida.writeUTF(mensaje);
        
        } catch (IOException e) {
            System.out.println("ay caramba");
        }
        
    }//GEN-LAST:event_btnFollowActionPerformed

    private void btnPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostActionPerformed
        if (this.usuario.status == Status.VIP) {
            try {
                String mensaje = txfPost.getText();
                txfFollow.setText("");
                usuario.salida.writeInt(2);
                usuario.salida.writeUTF(mensaje);

            } catch (IOException e) {
                System.out.println("ay caramba");
            }
        }
        
        if (this.usuario.status == Status.Regular) {
            try {
                String mensaje = txfPost.getText();
                String[] splitMcGoo = mensaje.split("/");
                usuario.salida.writeInt(3);
                usuario.salida.writeUTF(splitMcGoo[0]);
                usuario.salida.writeUTF(splitMcGoo[1]);

            } catch (IOException e) {
                System.out.println("ay caramba");
            }
            
            
        }

    }//GEN-LAST:event_btnPostActionPerformed

    private void txfPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCliente().setVisible(true);
            }
        });
    }
    
    public void mostrarUsuariosTotal (ArrayList<String> lista) {
        this.txaUsers.setText("");
        for(String nombre: lista) {
            this.txaUsers.append(nombre+"\n");
        }
    }
    
    public void mostrarFollowersFollowing (ArrayList<String> lista) {
        this.txaFollowersFollowing.setText("");
        for(String nombre: lista) {
            this.txaFollowersFollowing.append(nombre+"\n");
        }
    }
    
    public void showPost(String post, String author) {
        System.out.println("about to post " + post + " " + this.usuario.getUserName());
        
        this.txaBoard.append("""
                             ----------------------------------------------------------------
                             """);
        this.txaBoard.append(post + "\n" + "                by: " + author + "\n");
        this.txaBoard.append("""
                             ----------------------------------------------------------------
                             """);
//        JTextArea textArea = new JTextArea(post);
//        textArea.setEditable(false);
//        JScrollPane scrollPane = new JScrollPane();
//        scrollPane.setViewportView(textArea);
//        pnlBoard.add(scrollPane);
//        pnlBoard.revalidate();
//        pnlBoard.repaint();
//        this.revalidate();
//        this.repaint();
        
    }
    
    public void updateNoti (String message) {
        this.txaNotifications.setText(message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFollow;
    private javax.swing.JButton btnPost;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea txaBoard;
    private javax.swing.JTextArea txaFollowersFollowing;
    private javax.swing.JTextArea txaNotifications;
    private javax.swing.JTextArea txaUsers;
    private javax.swing.JTextField txfFollow;
    private javax.swing.JTextField txfPost;
    // End of variables declaration//GEN-END:variables
}
